export const fonts = {
    MontserratBlack: 'Montserrat-Black',
    MontserratBold: 'Montserrat-Bold',
    MontserratBoldItalic: 'Montserrat-BoldItalic',
    MontserratBlackItalic: 'Montserrat-BlackItalic',
    MontserratExtraBold: 'Montserrat-ExtraBold',
    MontserratExtraBoldItalic: 'Montserrat-ExtraBoldItalic',
    MontserratExtraLight: 'Montserrat-ExtraLight',
    MontserratExtraLightItalic: 'Montserrat-ExtraLightItalic',
    MontserratItalic: 'Montserrat-Italic',
    MontserratLight: 'Montserrat-Light',
    MontserratLightItalic: 'Montserrat-LightItalic',
    MontserratMedium: 'Montserrat-Medium',
    MontserratMediumItalic: 'Montserrat-MediumItalic',
    MontserratRegular: 'Montserrat-Regular',
    MontserratSemiBold: 'Montserrat-SemiBold',
    MontserratSemiBoldItalic: 'Montserrat-SemiBoldItalic',
    MontserratThin: 'Montserrat-Thin',
    MontserratThinItalic: 'Montserrat-ThinItalic',
    ComfortaaBold: 'Comfortaa-Bold',
    ComfortaaMedium: 'Comfortaa-Medium',
    ComfortaaLight: 'Comfortaa-Light',
    ComfortaaRegular: 'Comfortaa-Regular',
    ComfortaaSemiBold: 'Comfortaa-SemiBold',
};
